## Configuracion de Spring
spring:
  application:
    name: ms-books-payments
  datasource:
    #conexion a h2
    #url: jdbc:h2:mem:testdb;Mode=MySQL

    #conexion a postgresql
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres-15.railway.internal:5432/railway}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:BB-B321dEgEBG426C12aa1c6eA4EAgEa}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  #config de h2
  #h2:
  #  console:
  #    enabled: true
  #    path: /h2-console
  #    settings:
  #      web-allow-others: true

## Configuracion de Instancia 
server:
  port: 8089

## Configuracion del cliente de Eureka
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: ms-books-payments
